### ISSUE TITLE
Add docs in help for securely managing authentication

### ISSUE THREAD

**Issue by vortexing** [getwilds/proofr#19]
In the documentation of `proof_authenticate(username, password)` we might want to include some suggestions for how to not write your hutch password as inline code as a reminder or help for newbies.

**Comment by tefirman** [comment]
Love this suggestion!! Definitely think this should be added during v1.X

**Comment by dtenenba** [comment]
I wonder if there is a better/safer way to authenticate that does not involve using a password like this. Probably a v2 thing but we should think about it.

**Comment by sckott** [comment]
WRT dan's comment, there are some options (but this seems like a separate issue, whereas this one is just for documentation). 

- https://github.com/r-lib/askpass would allow us to make the user enter the password in a GUI that pops up so they don't add it in any code
- maybe magic link auth ? https://postmarkapp.com/blog/magic-links 
- I think https://github.com/r-lib/keyring could help store password in the OS specific keyring so that subsequent calls use that so passing the password not required, maybe, not totally sure

**Comment by dtenenba** [comment]
Yeah, for this one I was thinking (and maybe @vortexing was too) more along the lines of putting your password in an environment variable and then calling

```R
proof_authenticate("dtenenba", Sys.getenv("MYPASSWORD"))
```

Or putting it in a file. 
Anything to avoid the chance that it might get checked into a a github repo. 
We also want to avoid it going into R or bash command line history.

Maybe some of your suggestions above could apply to the token as well. If the user stores their token securely, then they only need to call proof_authenticate() once. That being the case, probably we should not put too much effort into storing the password in a keyring or similar. But we could do that for the token.

In V2 we should probably work on a lifecycle for the token (i.e. it expires after a certain time and if you try and use it, the API will tell you you need to log in with username and password again after which it gives you a new token).

**Comment by sckott** [comment]
> more along the lines of putting your password in an environment variable and then calling

yeah that's what I was going to add to the docs now, or thereabouts

Okay, new issue opened for the other auth/token stuff https://github.com/getwilds/proofr/issues/26

**Comment by sckott** [comment]
PR openedd
